### ISSUE TITLE
Cannot load checkpoints that script depends on 

### ISSUE THREAD

**Issue by motiwari** [lorraine2/implicit-hyper-opt#12]
Running `python train_augment_net2.py --use_augment_net` as suggested by the README results in:

```
Could not open finetuned_checkpoints/dataset:mnist_datasize:1600_hyperparam:weightDecayGlobal_seed:1.pkl
sailhome/motiwari/anaconda3/envs/ift-env/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3420: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/sailhome/motiwari/anaconda3/envs/ift-env/lib/python3.7/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/sailhome/motiwari/anaconda3/envs/ift-env/lib/python3.7/site-packages/numpy/core/_methods.py:262: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims, where=where)
/sailhome/motiwari/anaconda3/envs/ift-env/lib/python3.7/site-packages/numpy/core/_methods.py:222: RuntimeWarning: invalid value encountered in true_divide
  subok=False)
/sailhome/motiwari/anaconda3/envs/ift-env/lib/python3.7/site-packages/numpy/core/_methods.py:253: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "train_augment_net2.py", line 1181, in <module>
    do_legend=False, fontsize=fontsize)
  File "train_augment_net2.py", line 1004, in graph_val_prop_compare
    linewidth=linewidth)
  File "/sailhome/motiwari/anaconda3/envs/ift-env/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2777, in errorbar
    **({"data": data} if data is not None else {}), **kwargs)
  File "/sailhome/motiwari/anaconda3/envs/ift-env/lib/python3.7/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/sailhome/motiwari/anaconda3/envs/ift-env/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 3297, in errorbar
    raise ValueError("'x' and 'y' must have the same size")
ValueError: 'x' and 'y' must have the same size
```

**Comment by Asber777** [comment]
I come across the same problem, did you solve it?

**Comment by Asber777** [comment]
> Hi @Asber777 , we created a [fork](https://github.com/ThrunGroup/implicit-hyper-opt) of this repo to attempt to patch it but still couldn't get it to work.

thanks, I turn out to find that this function is for visualization, which don't matter and I delete it, lol
